@echo off 
REM Auto-generated by start-with-debug.bat 
REM Set all debug environment variables 
set RUST_LOG=terminal=debug,backend=debug,info 
set RUST_BACKTRACE=1 
set TERMINAL_DEBUG_REALTIME=1 
set TERMINAL_TRACE_ENABLED=1 
set TERMINAL_FREEZE_THRESHOLD=1000 
set TERMINAL_DEBUG_UI=1 
set TERMINAL_DEBUG_CHARTS=1 
cd /d "C:\Users\isich\xforce-terminal\" 
cargo run --release --bin terminal 
if errorlevel 1 goto TERMINAL_ERROR 
goto TERMINAL_SUCCESS 
:TERMINAL_ERROR 
echo. 
echo [ERROR] Terminal exited with error code 
echo [ERROR] Check the output above for error messages. 
echo [ERROR] Also check logs\debug-realtime.log for detailed logs. 
echo. 
pause 
:TERMINAL_SUCCESS 
